AWSTemplateFormatVersion: '2010-09-09'

Parameters:

  EnableSecretsBucket:
    Default: true
    Type: String
    AllowedValues: [true, false]

  EnableChefBucket:
    Default: true
    Type: String
    AllowedValues: [true, false]

  Env:
    Type: String

  Name:
    Type: String

Conditions:

  SecretsBucketEnabled:
    !Equals [true, !Ref EnableSecretsBucket]

  ChefBucketEnabled:
    !Equals [true, !Ref EnableChefBucket]

Resources:
  LoggingBucket:
    Condition: SecretsBucketEnabled
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: 'LogDeliveryWrite'

  SecretsBucket:
    Condition: SecretsBucketEnabled
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: 'Private'
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: 'secrets/'
      VersioningConfiguration:
        Status: Enabled

  SecretsBucketPolicy:
    Condition: SecretsBucketEnabled
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SecretsBucket
      PolicyDocument:
        Statement:
          -
            Sid: 'DenyIncorrectEncryptionHeader'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub "arn:aws:s3:::${SecretsBucket}/*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: 'AES256'
          -
            Sid: 'DenyUnEncryptedObjectUploads'
            Effect: 'Deny'
            Principal: '*'
            Action: 's3:PutObject'
            Resource: !Sub "arn:aws:s3:::${SecretsBucket}/*"
            Condition:
              'Null':
                s3:x-amz-server-side-encryption: 'true'

  ChefBucket:
    Condition: ChefBucketEnabled
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: 'Private'
      VersioningConfiguration:
        Status: Enabled

Outputs:
  LoggingBucket:
    Value: !If [SecretsBucketEnabled, !Ref LoggingBucket, '']

  SecretsBucket:
    Value: !If [SecretsBucketEnabled, !Ref SecretsBucket, '']

  ChefBucket:
    Value: !If [ChefBucketEnabled, !Ref ChefBucket, '']
